server:
  port: 8081
spring:
  application:
    name: "solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
adapters:
  r2dbc:
    host: "${DB_HOST_SOLICITUDES}"
    port: 3306
    database: "${DB_NAME_SOLICITUDES}"
    username: "${DB_USER_SOLICITUDES}"
    password: "${DB_PASSWORD_SOLICITUDES}"
adapter:
  restconsumer:
    timeout: 5000
    url: "${AUTH_SERVICE_URL}"
  sqs:
    region: "us-east-2"
    queues:
      colaNotificacion: "https://sqs.us-east-2.amazonaws.com/617669911828/cola-notificacion"
      colaRegistroSolicitud: "https://sqs.us-east-2.amazonaws.com/617669911828/cola-registro-solicitud"
      colaResultadoAutovalidacion: "https://sqs.us-east-2.amazonaws.com/617669911828/cola-resultado-auto-validacion"
      colaSolicitudAprobada: "https://sqs.us-east-2.amazonaws.com/617669911828/cola-solicitud-aprobada"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
entrypoint:
  sqs:
    region: "us-east-2"
    queueUrl: "https://sqs.us-east-2.amazonaws.com/617669911828/cola-resultado-auto-validacion"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
